import Head from 'next/head'
import Content from '../components/exchange/Content'
import styles from '../styles/Exchange.module.css'

export default function Exchange(props) {
  let defaultListData = props.listData;
  return (
    <div className={styles.container}>
      <Head>
        <title>Exchange</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <h1 className={styles.title}>
            Exchange Finder
          </h1>
          <h3>
            Find the cheapest and best exchanges to buy your crypto
          </h3>
        </div>
        <div className={styles.content}>
          <Content defaultListData={defaultListData}></Content>
        </div>


      </main>


    </div>
  )
}


export async function getServerSideProps(context){
  
  
  try{
    let data = await fetch("http://localhost:5000/exchange/cheapest?amount=100");
    data = await data.json();
    return {
      props : {"listData" : data}
    }
  }

  catch(error){
    return { 
      props : {
        "Error" : true,
        "Error" : error.toString(),

      }
    }
  }
}