import Head from 'next/head'
import Content from '../components/exchange/Content'
import styles from '../styles/Exchange.module.css'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Exchange</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <h1 className={styles.title}>
            Exchange Finder
          </h1>
          <h3>
            Find the cheapest and best exchanges to buy your crypto
          </h3>
        </div>
        <div className={styles.content}>
          <Content></Content>
        </div>


      </main>


    </div>
  )
}
