import { useEffect, useState } from 'react';
import io from 'socket.io-client';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Gas() {

  /**
   *  Handles all websocket communication for now
   *  this includes updating the gas fee when socket.io sends an update
  */
  useEffect(()=> {
    console.log("Connecting to the socket")
    const socket = io("http://localhost:5000");
    socket.on("EtherUpdate", (args)=>{
      setEtherPrice(args.GasFee)
    })
  }, [])

  /** React state for the ether gas fee*/ 
  const [etherPrice, setEtherPrice] = useState(0);


  //Layout of the gasfee page
  return (
    <div className={styles.container}>
      <Head>
        <title>Gas Fee Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the gas fee tracker!
        </h1>
  <p>The current gas price for ether is {etherPrice} gwei</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
