import { useEffect, useState } from 'react';
import io from 'socket.io-client';
import Head from 'next/head'
import Image from 'next/Image'
import styles from '../styles/Gas.module.css'


/**
 * Page with the listed gas prices for all of the coins
 */
export default function Gas() {

  /**
   *  Handles all websocket communication for now
   *  this includes updating the gas fee when socket.io sends an update
  */
  useEffect(()=> {
    console.log("Connecting to the socket")
    const socket = io("http://localhost:5000");
    socket.on("EtherUpdate", (args)=>{
      setEtherPrice(args.GasFee)
    })
  }, [])

  /** React state for the ether gas fee*/ 
  const [etherPrice, setEtherPrice] = useState(0);


  //Layout of the gasfee page
  return (
    <>
      <Head>
        <title>Gas Fee Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          Gas Prices Today
        </h3>
        <table className={styles.table}>
          <thead>
            <tr className={styles.row}>
              <th>Name</th>
              <th>GasFee(gwei)</th>
              <th>1hr(gwei)</th>
              <th>24hr(gwei)</th>
            </tr>
          </thead>
          <tbody>
            {/**A table row could be a possible component of its own */}
            <tr>
              <td>
                <Image
                src="/EthLogo.png"
                alt="Ethereum Logo"
                width={15}
                height={17}>
                </Image>
                Ethereum
              </td>
              <td>1200</td>
              <td>107</td>
              <td>120</td>
            </tr>
            <tr>
              <td>Solano</td>
              <td>1200</td>
              <td>107</td>
              <td>120</td>   
            </tr>    
            <tr>
              <td>Cardano</td>
              <td>1200</td>
              <td>107</td>
              <td>120</td>
            </tr>
            <tr>
              <td>Internet Computer</td>
              <td>1200</td>
              <td>107</td>
              <td>120</td>            
            </tr>
            <tr>
              <td>Polkadot</td>
              <td>1200</td>
              <td>107</td>
              <td>120</td>            
            </tr>
          </tbody>
        </table>
        
        {/*
        <table>
          <tr>
            <th>Name</th>
            <th>Gas Fee</th>
            <th>1hr</th>
            <th>24hr</th>
            <th>7d</th>
          </tr>
       
        </table>
           */}
      </main>

    </>
  )
}
